name: Checks
on:
  push:

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  checks:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install

      - name: Clean
        run: pnpm clean

      - name: Format
        run: pnpm fmt:check

      - name: Lint
        run: pnpm lint

      - name: Spellcheck
        run: pnpm spelling:check

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
